version: "3.5"

services:
  nest:
    container_name: nestjs
    build: ./NestJS/
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: user
    depends_on:
      - postgres
    ports:
      - 80:80
      - 5555:5555
    networks:
      - network
    volumes:
      - ssl_data:/etc/ssl_volume
      - nest_data:/root/Nestjs

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    networks:
      - network

  react:
    container_name: react
    build: ./React
    restart: always
    depends_on:
      - nest
    ports:
      - 3000:3000
    networks:
      - network
    volumes:
      - ssl_data:/etc/ssl_volume
      - react_data:/root/React

volumes:
  nest_data:
    driver: local
    driver_opts:
      type: none
      device: ./NestJS
      o: bind
  react_data:
    driver: local
    driver_opts:
      type: none
      device: ./React
      o: bind
  ssl_data:
    driver: local
    driver_opts:
      type: none
      device: ./ssl
      o: bind

networks:
  network:
    driver: bridge
