version: "3.5"

services:
  nest:
    container_name: nest
    build: ./NestJS/
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - UID=${UID}
      - SECRET=${SECRET}
      - DB_PORT=${DB_PORT}
      - FRONT_URL=${FRONT_URL}
      - BACK_PORT=${BACK_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIRECT_URI=${REDIRECT_URI}
    depends_on:
      - postgres
    ports:
      - ${BACK_PORT}:${BACK_PORT}
      - 5555:5555
    networks:
      - backend_network
    volumes:
      - ssl_data:/etc/ssl_volume
      - nest_data:/root/Nestjs

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend_network

  react:
    container_name: react
    build: ./React
    restart: always
    environment:
      - PORT=${FRONT_PORT}
      - REACT_APP_BACK_URL=${BACK_URL}
      - REACT_APP_FT_API=${FT_API}
    depends_on:
      - nest
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - ssl_data:/etc/ssl_volume
      - react_data:/root/React

volumes:
  nest_data:
    driver: local
    driver_opts:
      type: none
      device: ./NestJS
      o: bind
  react_data:
    driver: local
    driver_opts:
      type: none
      device: ./React
      o: bind
  ssl_data:
    driver: local
    driver_opts: 
      type: none
      device: ./ssl
      o: bind

networks:
  backend_network:
    driver: bridge
